// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHd2JjCPl1nDIN0JOMwlmffHwfKEBavkE',
    appId: '1:349424621203:web:1b3220271704b1b89d1f66',
    messagingSenderId: '349424621203',
    projectId: 'flutterfcm676',
    authDomain: 'flutterfcm676.firebaseapp.com',
    storageBucket: 'flutterfcm676.appspot.com',
    measurementId: 'G-RP3N1Q1VPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCK6hjS7rmk7HGLOUe3IxQxzdYyMzI2z0',
    appId: '1:349424621203:android:b8d7bfefd12da8459d1f66',
    messagingSenderId: '349424621203',
    projectId: 'flutterfcm676',
    storageBucket: 'flutterfcm676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj9Z668dBFYSbXSbQbd7Xc4wBLp6QU55g',
    appId: '1:349424621203:ios:a7ff39766f901c4d9d1f66',
    messagingSenderId: '349424621203',
    projectId: 'flutterfcm676',
    storageBucket: 'flutterfcm676.appspot.com',
    iosBundleId: 'com.example.flutterFcm1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj9Z668dBFYSbXSbQbd7Xc4wBLp6QU55g',
    appId: '1:349424621203:ios:8269beb36d66b7789d1f66',
    messagingSenderId: '349424621203',
    projectId: 'flutterfcm676',
    storageBucket: 'flutterfcm676.appspot.com',
    iosBundleId: 'com.example.flutterFcm1.RunnerTests',
  );
}
